spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mysql-mtom?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    boot:
        admin:
            client:
                url: http://cpms-monitor:5001
                username: admin
                password: admin
                instance:
                    prefer-ip: true
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
            config:
                refresh: true
                server-addr: localhost:8848
                file-extension: yml
                shared-configs:
                    - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

redis:
    host: 127.0.0.1
    password:
    port: 6379

management:
    endpoints:
        web:
            exposure:
                include: '*'

springfox:
    documentation:
        enabled: true

logging:
    level:
        com.post.m2m: debug
